services:
  web:
    build: .
    container_name: teamtasks_web
    command: daphne -b 0.0.0.0 -p 8000 core.asgi:application
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - db
      - redis

  botapi:
    build: .
    container_name: teamtasks_botapi
    command: uvicorn bot.http_api:app --host 0.0.0.0 --port 5000 --reload
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - web

  bot:
    build: .
    container_name: teamtasks_bot
    command: python bot/telegram_bot.py
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - botapi

  celery:
    build: .
    container_name: teamtasks_celery
    command: celery -A core worker -l info -P solo
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - web
      - redis

  celery-beat:
    build: .
    container_name: teamtasks_celery_beat
    command: celery -A core beat -l info
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - web
      - redis

  db:
    image: postgres:15
    container_name: teamtasks_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: teamtasks_redis
    ports:
      - "6379:6379"

volumes:
  pgdata: